name: iptv_checker_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^4.0.6
  flustars: ^2.0.1
  logger: ^1.1.0
  simple_animations: ^5.0.0+3
  m3u:
    git: https://github.com/uiiang/m3u-parse-utils.git
  settings_ui: ^2.0.2
  xml: any
  worker_manager: ^4.5.0
  iptv_check_manager:
    path: ../iptv_check_manager
  flutter:
    sdk: flutter

dependency_overrides:
  stream_channel: 2.1.1

dev_dependencies: 
  flutter_lints: 2.0.1
  test: ^1.21.4
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/categories.json
    - assets/countries.json
  uses-material-design: true

